driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-5.11
  - name: centos-6.7
  - name: centos-7.1
  - name: debian-7.8
  - name: debian-8.1
  - name: fedora-21
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: freebsd-9.3
  - name: freebsd-10.2

suites:
  - name: default
    run_list: fake::default
