driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6
  - name: centos-7
  - name: debian-8
  - name: debian-9
  - name: fedora-27
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: ubuntu-18.04
  - name: freebsd-11

suites:
  - name: default
    run_list: fake::default
