language: ruby
cache: bundler

dist: trusty

rvm: 2.3.3

# sudo required for hacky docker iptables fix
sudo: required

services: docker

env:
  matrix:
  - INSTANCE=default-ubuntu-1404
  - INSTANCE=default-ubuntu-1204
  - INSTANCE=default-centos-71

# Ensure we make ChefDK's Ruby the default
before_script:
  # https://github.com/zuazo/kitchen-in-travis-native/issues/1#issuecomment-142230889
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
script:
  - bundle exec chefstyle
  - bundle exec foodcritic . --exclude spec
  - bundle exec rspec
  - KITCHEN_LOCAL_YAML=.kitchen.docker.yml bundle exec kitchen verify ${INSTANCE}

branches:
  only:
    - master
